version: "3"
services:
  node1:
    image: stasbar/stellot-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    environment:
      - SELF=node1
      - HORIZON_ENABLED=true

  node2:
    image: stasbar/stellot-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    environment:
      - SELF=node2

  node3:
    image: stasbar/stellot-quickstart
    env_file: stellar-core.env
    command: "--privnet"
    environment:
      - SELF=node3
